// Authoritative firm→vcId map for deal-data firms.
// Section A (19): map to EXISTING vcs.json ids — no new entries needed.
// Section C (39): map to new ids that were appended to vcs.json by Task 3.
// Total: 58 entries (all distinct firms in data/source/vc_deals.json).

module.exports = {
  // ── Section A: existing entries ──
  "2048 Ventures":                  "2048-ventures",
  "8VC":                            "8vc",
  "Amplify Partners":               "amplify-partners",
  "Blackbird Laboratories Inc.":    "blackbird-laboratories-inc",
  "Catalio Capital Management":     "catalio-capital-management-lp",
  "Deerfield Management":           "deerfield-management-company-l-p",
  "Dimension":                      "dimension",
  "Ecphora Capital":                "ecphora-capital-management-company",
  "Emergence Capital":              "emergence-capital",
  "Felicis":                        "felicis",
  "Frazier Life Sciences":          "frazier-life-sciences",
  "Fusion Fund":                    "fusion-fund",
  "Hanabi Capital Management":      "hanabi-capital",
  "Lux Capital":                    "lux-capital",
  "Mayfield":                       "mayfield",
  "NEA":                            "nea",
  "Osage University Partners":      "osage-university-partners",
  "PTX Capital":                    "ptx-capital",
  "TCP Venture Capital":            "tcp-venture-capital",

  // ── Section C: new entries appended to vcs.json ──
  "500 Global":                     "500-global",
  "Alexandria Venture Investments": "alexandria-venture-investments",
  "Alta Partners":                  "alta-partners",
  "Baltimore Angels":               "baltimore-angels",
  "Barer & Son Capital, LLC":       "barer-son-capital-llc",
  "Blue Jay Syndicate":             "blue-jay-syndicate",
  "Brown Advisory":                 "brown-advisory",
  "Camden Partners":                "camden-partners",
  "Cowen Healthcare Investments":   "cowen-healthcare-investments",
  "Draper Associates":              "draper-associates",
  "Dreamit Ventures":               "dreamit-ventures",
  "Emerald Development Managers":   "emerald-development-managers",
  "Foresite Capital":               "foresite-capital",
  "Illumina Ventures":              "illumina-ventures",
  "Intermountain Ventures":         "intermountain-ventures",
  "Interwest Partners":             "interwest-partners",
  "Jump Start Foundry":             "jump-start-foundry",
  "Kairos Ventures":                "kairos-ventures",
  "Keiretsu Forum":                 "keiretsu-forum",
  "LionBird":                       "lionbird",
  "Longview Innovation":            "longview-innovation",
  "MPM Asset Management, LLC":      "mpm-asset-management-llc",
  "MedImmune Ventures":             "medimmune-ventures",
  "Morningside Group":              "morningside-group",
  "Northpond Ventures":             "northpond-ventures",
  "Novo Holdings":                  "novo-holdings",
  "OrbiMed":                        "orbimed",
  "Perceptive Advisors":            "perceptive-advisors",
  "Pfizer Ventures":                "pfizer-ventures",
  "Piedmont Capital Partners":      "piedmont-capital-partners",
  "RRE Ventures":                   "rre-ventures",
  "Redmile Group":                  "redmile-group",
  "Riptide Ventures":               "riptide-ventures",
  "Rock Spring Capital":            "rock-spring-capital",
  "S.R. One, Ltd.":                 "s-r-one-ltd",
  "Sands Capital Ventures":         "sands-capital-ventures",
  "Third Rock Ventures":            "third-rock-ventures",
  "Vivo Capital":                   "vivo-capital",
  "Windham Venture Partners":       "windham-venture-partners",
};
