'use strict';
/* Regenerates taxonomy.js from the venture-grade keyword taxonomy spreadsheet.
 *
 *   node scripts/convert_keyword_taxonomy.js      (or: npm run convert-taxonomy)
 *
 * Source of truth: data/source/VC_Keyword_Taxonomy_Venture_Grade.xlsx, sheet
 * "Keyword Summary" (columns: Keyword | Primary Bucket | Secondary Buckets).
 * ~324 keywords, each mapping to one primary + zero-or-more secondary of the 10
 * venture buckets. Output taxonomy.js is a dual classic-script + module.exports
 * module consumed by BOTH the browser (via <script defer>) and scoring.js (via
 * require). Do NOT hand-edit taxonomy.js — edit the xlsx and rerun this. */

const XLSX = require('xlsx');
const fs   = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '../data/source/VC_Keyword_Taxonomy_Venture_Grade.xlsx');
const OUT = path.join(__dirname, '../taxonomy.js');

const wb = XLSX.readFile(SRC);
const ws = wb.Sheets['Keyword Summary'];
if (!ws) throw new Error('Sheet "Keyword Summary" not found in ' + SRC);
const rows = XLSX.utils.sheet_to_json(ws);

// keyword -> { primary, secondary: [] }.  Keys normalized (lowercase, trimmed).
const taxonomy = {};
for (const r of rows) {
  const kw = (r['Keyword'] || '').trim().toLowerCase();
  const primary = (r['Primary Bucket'] || '').trim();
  if (!kw || !primary) continue;
  const secondary = (r['Secondary Buckets'] || '')
    .split(';').map(s => s.trim()).filter(Boolean);
  taxonomy[kw] = { primary, secondary };
}

const keys = Object.keys(taxonomy).sort();
const entries = keys.map(k => {
  const { primary, secondary } = taxonomy[k];
  const sec = JSON.stringify(secondary);
  return `  ${JSON.stringify(k)}: { primary: ${JSON.stringify(primary)}, secondary: ${sec} },`;
}).join('\n');

const banner =
`/* GENERATED by scripts/convert_keyword_taxonomy.js — DO NOT EDIT BY HAND.
 * Source: data/source/VC_Keyword_Taxonomy_Venture_Grade.xlsx ("Keyword Summary").
 * ${keys.length} keywords -> venture buckets (primary + secondary).
 *
 * Dual classic-script + module.exports (same pattern as scoring.js): the browser
 * loads this via <script defer src="taxonomy.js"> BEFORE scoring.js; Node reads it
 * via require('./taxonomy.js'). Besides the generated VC_KEYWORD_TAXONOMY map, this
 * file carries the hand-maintained crosswalk that translates the 10 venture buckets
 * back onto JHTV's 8 display domains (the tech catalog is unchanged).  To change the
 * keyword map: edit the xlsx and rerun the converter. To change the crosswalk /
 * overlays: edit the CROSSWALK block inside the converter, then rerun. */
'use strict';
`;

// The crosswalk + overlays are authored here (not in the xlsx) so a single command
// regenerates the whole module. Emitted verbatim into taxonomy.js.
const crosswalkBlock =
`// New 10 venture buckets -> JHTV's 8 display domains. Buckets with no JHTV tech
// (Robotics/AI/Software, Industrial & Manufacturing, Aerospace/Defense/Quantum)
// map to null and contribute no sector credit for this biotech-heavy catalog.
const BUCKET_TO_DOMAIN = {
  'Therapeutics':                 'Therapeutics',
  'Diagnostics':                  'Diagnostics',
  'Digital Health':               'Digital Health',
  'Medical Devices':              'Medical Devices',
  'Research Technologies':        'Research Technologies',
  'Climate & Clean Tech':         'Clean Tech',
  'Agricultural & Food Tech':     'Agricultural Tech',
  'Robotics, AI & Software':      null,
  'Industrial & Manufacturing':   null,
  'Aerospace, Defense & Quantum': null,
};

// The new taxonomy folded cybersecurity into "Robotics, AI & Software" (which we
// drop), but JHTV has 3 cyber-tagged techs + many VC cyber mentions. Preserve them:
// these terms yield the JHTV "Cybersecurity" domain as PRIMARY (mirrors the old
// INDUSTRY_TO_DOMAIN behavior for cyber).
const CYBER_KEYWORDS = [
  'cybersecurity', 'cyber security', 'cyber', 'infosec', 'information security',
  'security', 'national security', 'zero trust',
];

// JHTV's 8 display-domain names, lowercased, each mapping to itself as PRIMARY.
// Guarantees enriched VC sectors[] (written AS domain names) round-trip, and covers
// "agricultural tech" which is absent from the taxonomy keyword list.
const DOMAIN_SELF_MAP = {
  'therapeutics':          'Therapeutics',
  'diagnostics':           'Diagnostics',
  'digital health':        'Digital Health',
  'medical devices':       'Medical Devices',
  'research technologies': 'Research Technologies',
  'clean tech':            'Clean Tech',
  'agricultural tech':     'Agricultural Tech',
  'cybersecurity':         'Cybersecurity',
};

// Broad/low-information terms that shouldn't pin a single domain — flagged as
// "matches all", scored as a weak catch-all (0.5) only when nothing specific hit.
const CATCH_ALL = ['deep tech', 'healthcare', 'health care'];
`;

const body =
`${banner}
const VC_KEYWORD_TAXONOMY = {
${entries}
};

${crosswalkBlock}
if (typeof module !== 'undefined' && module.exports)
  module.exports = { VC_KEYWORD_TAXONOMY, BUCKET_TO_DOMAIN, CYBER_KEYWORDS, DOMAIN_SELF_MAP, CATCH_ALL };
`;

fs.writeFileSync(OUT, body);
console.log(`Wrote ${keys.length} keywords to taxonomy.js`);
